# Enable the github stale issue bot tracker
name: "Add comment to issues marked invalid"
on:
  issues:
      types: [labeled]
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            if (context.payload.label.name != "invalid")
              return;
            msg = "Unfortunately, it appears the directions at"
                + " https://www.klipper3d.org/Contact.html"
                + " were not followed for this issue.\n"
                + "\n"
                + "We use github for collaborators working on improving"
                + " Klipper. If you have a problem with your printer,"
                + " have a question, or have an idea for a feature, then"
                + " you need to follow the directions at:"
                + " https://www.klipper3d.org/Contact.html\n"
                + "\n"
                + "This ticket will be automatically closed.\n"
                + "\n"
                + "Best regards,\n"
                + "~ Your friendly GitIssueBot\n"
                + "\n"
                + "PS: I'm just an automated script, not a human being.";
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
